// Programmatically build a Jupyter notebook (.ipynb JSON) for a curriculum
// week, following the exact 8-cell structure defined in CLAUDE.md Section 16.4.
// Returns the notebook as a JSON string.

function mdCell(lines) {
  return { cell_type: "markdown", metadata: {}, source: splitSource(lines) };
}

function codeCell(lines) {
  return {
    cell_type: "code",
    execution_count: null,
    metadata: {},
    outputs: [],
    source: splitSource(lines),
  };
}

// Jupyter stores source as an array of lines, each ending in \n except the last.
function splitSource(text) {
  const arr = text.split("\n");
  return arr.map((l, i) => (i === arr.length - 1 ? l : l + "\n"));
}

export function generateNotebook(phase, week) {
  const project = week.project || {};
  const N = week.week;
  const installs = week.colab_installs || [];
  const runtimeNote =
    week.colab_runtime === "GPU"
      ? "GPU (Runtime → Change runtime type → T4 GPU)"
      : week.colab_runtime || "CPU";

  const criteria = (project.evaluation_criteria || [])
    .map((c, i) => `${i + 1}. ${c}`)
    .join("\n");

  // Cell 1 — Header & Setup (markdown)
  const cell1 = mdCell(
    `# NeuralPath — Week ${N}: ${week.title}
> Generated by NeuralPath desktop app. Run each cell in order.
> **Runtime required:** ${runtimeNote}

## Objectives
${project.description || ""}

## Evaluation Criteria
${criteria}`
  );

  // Cell 2 — Environment setup (code)
  const installLines =
    installs.length > 0
      ? installs.map((p) => `install(${JSON.stringify(p)})`).join("\n")
      : "# (no extra packages required for this week)";
  const cell2 = codeCell(
    `# ── Environment Check ──
import subprocess, sys

def install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

# Week-specific installs
${installLines}

import torch
print(f"PyTorch: {torch.__version__}")
print(f"GPU available: {torch.cuda.is_available()}")
print(f"Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")`
  );

  // Cell 3 — Google Drive mount (code)
  const cell3 = codeCell(
    `# ── Mount Google Drive (for saving checkpoints & results) ──
from google.colab import drive
drive.mount('/content/drive')

import os
SAVE_DIR = '/content/drive/MyDrive/NeuralPath/Week${N}'
os.makedirs(SAVE_DIR, exist_ok=True)
print(f"Save directory: {SAVE_DIR}")`
  );

  // Cell 4 — Dataset download (code) — per-week from curriculum
  const cell4 = codeCell(
    week.colab_dataset_setup ||
      `# ── Dataset Setup ──
# This week has no predefined dataset download. Load your data here.
print("Add your dataset loading code here.")`
  );

  // Cell 5 — Starter code (code)
  const cell5 = codeCell(
    `# ── Project Starter Code (same scaffold as the NeuralPath app) ──
${project.starter_code || "# (no starter code provided)"}`
  );

  // Cell 6 — USER WORK ZONE (code)
  const cell6 = codeCell(
    `# ${"=".repeat(62)}
# YOUR IMPLEMENTATION — Write your solution below
# ${"=".repeat(62)}

# TODO: Implement the project objectives listed in Cell 1`
  );

  // Cell 7 — Evaluation & Results export (code)
  const cell7 = codeCell(
    `# ── Results Export ──
# Run this cell AFTER completing your implementation.
# It saves a results.json that you import back into NeuralPath.

import json
from datetime import datetime

results = {
    "week_id": "p${phase.phase}_w${N}",
    "week_title": ${JSON.stringify(week.title)},
    "completed_at": datetime.now().isoformat(),
    "metrics": {
        "primary_metric_name": "val_accuracy",   # e.g. mAP@50, val_loss, FID
        "primary_metric_value": None,             # replace with your actual value
        "secondary_metrics": {}                   # any other metrics you tracked
    },
    "self_notes": "",   # Write a brief note about your implementation
    "model_saved_path": f"{SAVE_DIR}/model_final.pt"
}

with open('/content/results.json', 'w') as f:
    json.dump(results, f, indent=2)

with open(f'{SAVE_DIR}/results.json', 'w') as f:
    json.dump(results, f, indent=2)

print("✅ results.json saved.")
print("Next step: Download /content/results.json and import it into NeuralPath.")
print(json.dumps(results, indent=2))`
  );

  // Cell 8 — Download helper (code)
  const cell8 = codeCell(
    `# ── Download results.json to your machine ──
from google.colab import files
files.download('/content/results.json')`
  );

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: { display_name: "Python 3", language: "python", name: "python3" },
      language_info: { name: "python" },
      colab: { provenance: [] },
      accelerator: week.colab_runtime === "GPU" ? "GPU" : "None",
    },
    cells: [cell1, cell2, cell3, cell4, cell5, cell6, cell7, cell8],
  };

  return JSON.stringify(notebook, null, 1);
}
