// Reads the Wolfram-generated PNGs in assets/plots/ and emits
// src/curriculum/plots.js as base64 data URIs. Data URIs keep the plots
// bundle-proof (no path resolution across dev/prod/Electron) and CSP-safe
// (index.html allows `img-src 'self' data:`).
//
// Re-run after regenerating any plot:  node scripts/buildPlots.mjs

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLOTS_DIR = resolve(__dirname, "../assets/plots");
const OUT = resolve(__dirname, "../src/curriculum/plots.js");

// One-line caption per plot key (used under the figure in the tooltip).
const CAPTIONS = {
  sigmoid:
    "The logistic sigmoid squashes any real number into (0, 1) — the output unit of logistic regression and a classic activation.",
  activations:
    "ReLU, GELU and Swish — the nonlinearities that let a network model curves instead of just straight lines.",
  "cross-entropy":
    "Cross-entropy loss stays small while the model is confident and correct, but explodes as the probability assigned to the true class approaches 0.",
  "gradient-descent":
    "Gradient descent steps downhill along the slope; the steps shrink automatically as the gradient flattens near the minimum.",
  "normal-distribution":
    "The Gaussian (normal) distribution: the mean sets its center, the variance sets its spread.",
  "bias-variance":
    "As model complexity grows, training error keeps falling while validation error turns back up — the right side is the overfitting regime.",
  eigenvector:
    "A matrix stretches the unit circle into an ellipse. Eigenvectors are the special directions it only scales — by the eigenvalue — never rotates.",
  "pca-variance":
    "A PCA scree plot: how much of the data's variance each principal component explains. The first few components usually dominate.",
  "roc-curve":
    "The ROC curve trades true-positive rate against false-positive rate; the area under it (AUC) summarizes how well the model ranks positives above negatives.",
  elbow:
    "Cluster inertia drops as k grows; the 'elbow' marks the point of diminishing returns — a heuristic for choosing k.",
  kmeans:
    "k-means assigns each point to the nearest of k centroids, then moves each centroid to the mean of its members, and repeats.",
  regularization:
    "Ridge (L2) constrains the weights to a circle, Lasso (L1) to a diamond. The diamond's corners are why Lasso drives weights to exactly zero.",
  "entropy-gini":
    "Both impurity measures peak at a 50/50 split and vanish at a pure node — a decision tree picks the split that reduces them the most.",
  "confusion-matrix":
    "Counts of predicted vs. actual labels. Precision, recall and F1 are all just ratios of these four cells.",
  "lr-schedule":
    "Learning-rate schedules anneal the step size during training — cosine decays smoothly, step decay drops it at fixed milestones.",
};

const files = readdirSync(PLOTS_DIR).filter((f) => f.endsWith(".png"));
files.sort();

const entries = files.map((f) => {
  const key = basename(f, ".png");
  const b64 = readFileSync(resolve(PLOTS_DIR, f)).toString("base64");
  const caption = CAPTIONS[key] || "";
  return { key, src: `data:image/png;base64,${b64}`, caption };
});

const body = entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.key)}: {\n    caption: ${JSON.stringify(
        e.caption
      )},\n    src: ${JSON.stringify(e.src)},\n  },`
  )
  .join("\n");

const out = `// AUTO-GENERATED by scripts/buildPlots.mjs — do not edit by hand.
// Educational figures rendered with Wolfram Language and embedded as base64
// data URIs so they ship inside the offline app bundle (CSP: img-src 'self' data:).
// Each entry: { caption, src }. Referenced from src/curriculum/glossary.js.

export const PLOTS = {
${body}
};
`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT} with ${entries.length} plots:`);
console.log(entries.map((e) => `  - ${e.key}`).join("\n"));
